In [2]:
import pandas as pd

In [3]:

df =pd.read_csv('../dataset/planilha_202301.csv', sep=';', 
                                    encoding='utf-8', 
                                    thousands='.', 
                                    decimal=',', 
                                    usecols=['data_base', 'uf', 
                                             'carteira_ativa', 'ativo_problematico', 'numero_de_operacoes',
                                             'carteira_inadimplida_arrastada', 'cliente', 
                                             'modalidade', 'porte', 'ocupacao', 'cnae_secao'])

In [23]:
df1= df.query('uf=="GO"')
df1.head()

,data_base,uf,cliente,ocupacao,cnae_secao,porte,modalidade,numero_de_operacoes,carteira_ativa,carteira_inadimplida_arrastada,ativo_problematico
166978,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Cartão de crédito,<= 15,9.040131e+04,0.00,0.00
166979,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Cartão de crédito,11061,6.983004e+07,1313586.17,2202817.85
166980,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Cartão de crédito,<= 15,4.349160e+04,43491.60,43491.60
166981,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Empréstimo com consignação em folha,4351,2.765154e+08,5366914.92,9263124.79
166982,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Empréstimo com consignação em folha,<= 15,2.519401e+04,25194.01,25194.01

In [33]:
df1.loc[df1['numero_de_operacoes']== '<= 15', 'numero_de_operacoes'] = 7

In [34]:
df1.head()

,data_base,uf,cliente,ocupacao,cnae_secao,porte,modalidade,numero_de_operacoes,carteira_ativa,carteira_inadimplida_arrastada,ativo_problematico
166978,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Cartão de crédito,7,9.040131e+04,0.00,0.00
166979,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Cartão de crédito,11061,6.983004e+07,1313586.17,2202817.85
166980,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Cartão de crédito,7,4.349160e+04,43491.60,43491.60
166981,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Empréstimo com consignação em folha,4351,2.765154e+08,5366914.92,9263124.79
166982,2023-01-31,GO,PF,PF - Aposentado/pensionista,-,PF - Acima de 20 salários mínimos,PF - Empréstimo com consignação em folha,7,2.519401e+04,25194.01,25194.01